### ISSUE TITLE
Block "parent" scroll when drawer is open

### ISSUE THREAD

**Issue by geracolo** [CodyHouse/cd-drawer-changelog#1]
Hi there! First time ever posting an issue on github, I create an account especially to suggest an improvement on the drawer component. 
The suggestion is to block the "parent" scroll when the drawer is open. When you reach either bottom or top of the drawer and you still scroll (looking for more content for example), it becomes to scroll the content behind the drawer. When that happens, and you close the drawer, you're navigating in a different section from when the drawer was trigger initially. 
I hope I made myself clear!
By the way, you've done an amazing job!
Cheers from Patagonia, Argentina. 
Gera.

**Comment by claudia-romano** [comment]
Hi Gera, thanks for the suggestion! 
We have just pushed a new version of the component that includes this suggestion.  You can get the updated style here:
https://codyhouse.co/ds/components/app/drawer

Cheers!

**Comment by geracolo** [comment]
Hi Claudia, thanks for considering my suggestion! Just to point out, I've refreshed both the scss and js files, recompiled and checked the update on Chrome and Safari. In Chrome works as expected, but in Safari stills scrolling the parent when the end of the drawer is reached (I assumed its because overscroll-behavior isn't compatible with Safari). 
Hope this helps!
Cheers!

**Comment by claudia-romano** [comment]
Hi there, yes we have used the overscroll-behavior css property. It is supported in all modern browsers except Safari:
https://caniuse.com/#feat=css-overscroll-behavior

That is why you see it is working in Chrome but not Safari. 
The alternative solution would be to add an ```overflow: hidden``` to the body element when the drawer is open; but this is something that could create issues depending on the page content so we won't be including it as a default.

If you need this to work on Safari as well, you could use the showDrawer and closeDrawer functions (defined in the component js file) to add/remove that from the body. For example, in the showDrawer, add:
```document.body.style.overflow = "hidden";```

Hope this helps! Cheers

**Comment by geracolo** [comment]
Hi there again, thanks Claudia! I've just updated the js file to toggle the body overflow from "auto" to "hidden" on closeDrawe / showDrawer functions and works for me. 
Thanks for your time!
Cheers!
