### ISSUE TITLE
Support for animated menu button / single button

### ISSUE THREAD

**Issue by w3work** [CodyHouse/cd-drawer-changelog#2]
Hi CodyHouse,

i want to use the Drawer (Modal version) for a Navigation in a website project.
Actually the Drawer Component is build with a "Show" button and a "Close" button. It would be very nice and highly recommended if you could implemenet a single button solution. So show and close are the same button. :)
In my website project i want to implement the "Animated menu button" component:
Click the button -> Drawer opens -> Animated button state is X (anim-menu-btn--state-b)
Click the button again -> Drawer close -> Animated button state is Hamburger (anim-menu-btn)

**Comment by sebastiano-guerriero** [comment]
Hi there, we'll update the component so that the trigger works as a toggle: this way, you can add the aria-controls="drawer-id" to any button you want, and it can be used to both open and close the drawer.

**Comment by sebastiano-guerriero** [comment]
We've just shipped an update: now the control of the drawer is a toggle. You can use it to control the opening/closing of the drawer. All that is required is setting the correct aria-controls value (just like before) :)

**Comment by w3work** [comment]
Hi Sebastiano,
thank you for fixing this so quickly. Really great! 👍
