### ISSUE TITLE
Show the modal manaually

### ISSUE THREAD

**Issue by omarherri** [CodyHouse/cd-drawer-changelog#3]
Hi, this is not a bug but a question.
I was able to operate the component. But for my own purpuses i wanted the modal to be displayed as soon as I refresh the page, so i added the class 'drawer--is-visible'. the thing is when i click on close button the modal remains displayed.
I tried to look at the javascript code, bun i'm more a php developper so is there any way to make it work?

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads up.
We just pushed an update to the drawer component fixing this issue. You can get the new js code from the component page:
https://codyhouse.co/ds/components/app/drawer

Cheers

**Comment by omarherri** [comment]
Thank you, you are the best, it works like a charm.
