### ISSUE TITLE
Util is not defined

### ISSUE THREAD

**Issue by jit3ndra** [CodyHouse/cd-drawer-changelog#4]
I have added the code to my page following the instructions as available on https://codyhouse.co/ds/components/app/drawer , however when I run the code it is throwing an error called "Util is not defined".

Please help.

**Comment by claudia-romano** [comment]
Hi there,
CodyHouse components are based on [CodyFrame](https://codyhouse.co/ds/docs/framework).

For them to work properly, you'll need to import both the style of the framework and the util.js file of the framework (that includes a list of utility functions we use in our components):
https://codyhouse.co/ds/docs/framework#content

It looks like you are not importing the util.js file. Importing it will fix the issue.

Feel free to reopen this if you are still experiencing the problem. Cheers.
