### ISSUE TITLE
Open "Drawer" via freshly created items don't work

### ISSUE THREAD

**Issue by addwot** [CodyHouse/cd-drawer-changelog#7]
Worked perfectly for Lazyload component with
`new LazyLoad(document.querySelectorAll('[loading="lazy"]'));`

but for Drawer, it doesn't work, got "`Drawer is not defined`"

**Comment by addwot** [comment]
Converting the Drawer `function` to `class` resolved my problem.

Now call `new Drawer(element);` after elements dynamically added

**Is this method the best so far?**

![image](https://user-images.githubusercontent.com/4226169/116451575-553a9d00-a865-11eb-9d0b-1403044ecb65.png)

**Comment by claudia-romano** [comment]
Hi there, we have just pushed an updated version of the Drawer component where the `Drawer` object is now public so you can call `new Drawer(element)` from your custom code. 
You can get the updated code here:
 https://codyhouse.co/ds/components/app/drawer

Cheers!
